### ISSUE TITLE
`mate-panel --replace` must be invoked after compiz to work properly

### ISSUE THREAD

**Issue by thassan** [mate-desktop/mate-panel#249]
same or similar to what is described here: http://forums.linuxmint.com/viewtopic.php?f=206&t=169308 (Compiz mucks with mate-panel on startup)

In my case/setup, the top panel is clickable, the bottom panel isn't. Even right clicking the bottom panel brings up the right click menu of the desktop, as if it was invisible.

This happens even when using gtk-window-decorator in place of marco, and happens even if compiz is set as the window-manager in dconf.

Tested on Linux Mint 17 Qiana, Compiz 1:0.9.11.2+14.04.20140714-0ubuntu1, mate-panel 1.8.0-0+qiana

**Comment by monsta** [comment]
@thassan: how's the situation in Mint 17.1 Rebecca? I know Clem did some work to make compiz work better in Mint, so maybe the issue is already fixed.

**Comment by NiceandGently** [comment]
@thassan
Did you try out the 'force GLX to X' in ccsm workaround plugin?
This fixes the issue here in fedora.

**Comment by thassan** [comment]
i believe the issue has been fixed in Mint 17.1 Rebecca.

**Comment by NiceandGently** [comment]
@thassan
can you please close the report if it is fixed, i don't have the rights to do that.
Thank you

**Comment by lukefromdc** [comment]
I can confirm this is still an issue, I've never had compiz and mate-panel NOT act like this, and in my setup for compiz added to Debian have to play timing games to get everything working on a session start. I normally use "killall mate-panel" and let it restart to avoid busy cursor issues.

This is with or without the workarounds. OpenGL is Mesa/r600 AMD, mate-panel is all recent versions, all of them built with GTK3, currently on mate-panel 1.17.0 built with GTK 3.22.2

**Comment by rocketman1337345** [comment]
This is still an issue 3 years after being reported, fix it by 

`compiz --replace & `

and then directly afterwards calling 

`mate-panel --replace`

**Comment by alexarnaud** [comment]
Le 19/04/2017 à 16:58, Homeless Cat a écrit :
> This is still an issue 3 years after being reported, fix it by

What is your environment ? I use Mate 1.8 with Compiz 0.9.12.2 on Debian 
8.7 without this issue. I run compiz from an autostart desktop file with 
the command "compiz --replace".
You could try this also on Debian stretch/sid with the new Compiz 0.9 
package.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by rocketman1337345** [comment]
@alexarnaud 

My environment is so

`uname -r `

4.9.0-kali3-amd64

`mate-about`

Mate Desktop Environment 1.16.1

`compiz --version`

Compiz 0.9.13.0

**Comment by lukefromdc** [comment]
I can assure you this is still an issue in my Debian Unstable setup, probably Mint is using some kind of startup script to ensure the panel always restarts after compiz, just as I include in my locally compiled compiz packages. Proof of the issue is that compiz --replace must always be followed by killlall mate-panel(to avoid busy cursor issue) or mate-panel --replace.  

This has literally been an issue since compiz first came out as far as I can recall. Compiz itself is extremely complex, and is known for acting in a number of ways differently than any other window manager. I have no idea at all how to fix this other than restarting the panel after compiz at every session start-which is exactly how it had to work in the old days. In my locally compiled compiz packages I also had to

**Comment by monsta** [comment]
Calling @clefebvre and @flexiondotorg for help, since Mint and Ubuntu MATE have some helper script(s) to work around this, as I understand it.

**Comment by muktupavels** [comment]
Is there open bug for compiz in launchpad.net?

**Comment by monsta** [comment]
I found two bug reports that might be related to this one:
https://bugs.launchpad.net/bugs/1390157
https://bugs.launchpad.net/bugs/1579421

The last report is also mirrored here at https://github.com/mate-desktop/mate-panel/issues/495.
I'm not sure if it's exactly the same as what happens for reporters here. I only know that the workaround (restarting the panel) is the same.

Do you have these problems with gnome-panel as well?

**Comment by muktupavels** [comment]
https://code.launchpad.net/~muktupavels/compiz/fix-initial-server-frame-position/+merge/322817

**Comment by lukefromdc** [comment]
I can confirm that 
https://code.launchpad.net/~muktupavels/compiz/fix-initial-server-frame-position/+merge/322817
Fixes the unresponsive panel after starting or restarting compiz. I still have a Debian-specific issue where compiz itself won't properly start if specified in org>mate>desktop>session>required-components>windowmanager so I can't quite say for sure how a default startup will work in Ubuntu. Still, in Debian this fixes the panel issue, so once Ubuntu merges the fix this can be closed. Ubuntu hasn't updated compiz since Jan 9, this will remain a problem until they do.

For my part I've added the fix to my own compiz branch on Github.
https://github.com/lukefromdc/compiz
Since I don't know how to pull and merge anything from bzr to git, that's all done by hand. Any way to edit the author fields in git commits to reflect credit to Albert?

**Comment by muktupavels** [comment]
It will be merged soon - https://bileto.ubuntu.com/#/ticket/2730...

P.S. In git you have --author and --date options... git commit --author '...' --date='...' ...

**Comment by lukefromdc** [comment]
Most of my git work is done in git-gui except for rebases and merges, I can't find options there for resetting authorship so for now the author gets mentioned in the commit message

**Comment by muktupavels** [comment]
Oh, I dont use GUI for that... Anyway, don't worry - I don't care if commit has my name or not...

**Comment by monsta** [comment]
Ok, the fix landed in Compiz, according to https://bugs.launchpad.net/bugs/1579421, so closing this one.
