### ISSUE TITLE
Windows maximize 'under' panels

### ISSUE THREAD

**Issue by sanderboom** [mate-desktop/mate-panel#303]
In certain setups (e.g. dual monitor positioned vertically) I notice that the bottom panel of the top monitor and the top panel of the bottom 'cover' any maximized windows. 

It seems that the area that these panels take up are denoted as available space for windows, while it should not.
##

**Comment by monsta** [comment]
Does it affect only maximized windows?

**Comment by monsta** [comment]
Also, does it happen *only* with more than one monitor?

**Comment by mrchapp** [comment]
It happens with just one monitor too (laptop display in my case), no special setup. If I change the display resolution and back again to what it was, then maximizing works as expected.

**Comment by raveit65** [comment]
Are you using compiz?

**Comment by mrchapp** [comment]
Nope, plain Marco. Interesting bit is that when that happens a maximized window is not represented as occupying a 100% of the space in the workspace switcher, but rather like a quarter of it in the top most left corner of the workspace; same goes for all workspaces.

I'll take a snapshot next time that happens.

**Comment by mrchapp** [comment]
Pluma's status bar hiding behind the panel; window size in workspace switcher is not accurate.

![marco-maximized](https://cloud.githubusercontent.com/assets/27009/12252198/ca154a46-b89a-11e5-85b8-6d33a91cc1d7.png)

**Comment by kocmo** [comment]
+1, me too

I'm also affected, I run Mate on Mint 17.3, with 2 monitors (top monitor as main), and windows maximize under panel.

**Comment by gpezza2** [comment]
I realize this is an old thread, but I'm having the same issue on Mate running on CentOS 7, no Compiz, nVidia K1200 with proprietary drivers.  Any hopes of a solution?

**Comment by ParikhMeet** [comment]
+1
I am also having the same issue on Mate environment in Parrot OS.

**Comment by kocmo** [comment]
Workaround: I resolved it by moving the panel to the top of the top monitor. The problem went away.

**Comment by flexiondotorg** [comment]
@monsta I've reproduced this. It only happens on dual monitors with vertical panels on the monitor which is not the primary. The panels must also not be at the monitor edge.

So with 2 monitors side by side and to left most monitor is primary, it will only happen if you place a vertical panel on the right hand monitor on the left of that monitor.

**Comment by ParikhMeet** [comment]
@kocmo I like the old Gnome 2 style of having panels both at the top and bottom of the panel. The top panel is fine, its the bottom panel that is having this behavior.

**Comment by ParikhMeet** [comment]
@flexiondotorg I have only one primary monitor and yet this issue is observed.

**Comment by turgs** [comment]
I just noticed this too... and fixed it by changing the _Window Manager_ in _MATE Tweak_ to **Marco (Software compositor)** from **Marco (Compton GPU compositor)**

**Comment by turgs** [comment]
**Update:** My note [above](https://github.com/mate-desktop/mate-panel/issues/303#issuecomment-354698485) doesn't fix it like I thought.

However, when I toggle _Undecorate maximized windows_ on/off in _Mate Tweak_ it fixes it self.. although I'm assuming this may only be a temporary fix.

![Image of Undecorate maximized windows](https://i.stack.imgur.com/n9Jjh.png)

**Comment by monsta** [comment]
Well I have no idea why it happens... I would try changing window manager to Metacity or Compiz and see what happens. Might be something in a WM instead of mate-panel.

**Comment by Xyrop** [comment]
Hello,
I have exactly the same issue. Ubuntu-mate distro + compiz activated (ccsm & all).
Reorganizing displays make the windows maximize correctly, as long as the panel is not "between" two displays.
Thanks

**Comment by MartinX3** [comment]
Same problem in Linux Mint 18.3 x64 Mate and Ubuntu Mate x64 17.10
I have 2-3 Monitors, but the panels are on only one monitor.
When I use more than ONE panel, one of them get ignored by the maximized applications.

**Comment by PierreS1** [comment]
Same problem.
My laptop is the bottom monitor and my desk screen the top one.
I'd like to keep the laptop screen as the primary monitor, but I can't, windows are hidden by the MATE panel, looking for a solution.

**Comment by PierreS1** [comment]
Same problem.
My laptop is the bottom monitor and my desk screen the top one.
I'd like to keep the laptop screen as the primary monitor, but I can't, windows are hidden by the MATE panel. Looking for a solution.

**Comment by MartinX3** [comment]
Not fixed in Ubuntu 18.04 x64 with Mate 1.20.1

**Comment by monsta** [comment]
@vkareh: can you please take a look at this...?

**Comment by vkareh** [comment]
@monsta - yes, I can confirm this issue. The panel struts size calculation doesn't seem to take into account inside edges (e.g. top of bottom monitor). It's been on my to do list since last year, since it affects me. But I'll re-prioritize, since it seems to affect a lot of people

**Comment by rflbianco** [comment]
Great to know that this issue has been re-prioritized. I'm having the exact same behavior described by @Xyrop. Also using Ubuntu MATE (18.04 LTS - MATE 1.20.1).

I have 2 different multi-monitor setups:
- home: 2 x 1080p monitors side-by-side, left monitor primary
- work: laptop (720p) centralized between and below 2 x 1080p monitors side-by-side, laptop screen primary.

I use the Mutiny panel arrangement and there is no problem with my HOME setup. However, in the 3 monitors setup, the maximized windows stretch under the top panel (for appmenu and indicators). Therefore I have either the window decoration or part of the actual application window (depending of `Undecorate maximized windows` state) hidden under the panel.

So, it seems, as observed by @Xyrop and taking my use cases, that the problem only occur when the panel is between displays.

**Comment by phocean** [comment]
Here is a bounty in case more people want to participate:

https://www.bountysource.com/issues/57959471-panel-issues-in-dual-screen-layouts-overlapping-window-decoration-broken-hiding-behavior

**Comment by monsta** [comment]
This issue actually has its own bountysource link, but due to their plugin being buggy, the formatting was screwed up. I've manually edited the first post to make the bounty links appear.

**Comment by muktupavels** [comment]
https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472580736

> This property MUST be set by the Client if the window is to reserve space at the edge of the **screen**. The property contains 4 cardinals specifying the width of the reserved area at each border of the **screen**, and an additional 8 cardinals specifying the beginning and end corresponding to each of the four struts.

The problem here is that this specifications has been written in times when multiple monitors on one screen was not popular thing... It was possible to have multiple screens and each screen had one monitor.

There is simply no way to reserve area in middle of screen... To fix this we need update/extend specification in way that allows to set struts for each monitor not screen with well defined behavior what should happen when wm or toolkit or app does not support updated specification.

Struts are used to calculate workarea:
https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472697552

And workarea also is not monitor aware... So also that would need update. After updating you would have to update/fix window managers, toolkits and applications. So not only you would have to fix marco and mate-panel, but also gtk, qt...

**Comment by vkareh** [comment]
@muktupavels - can't this be done with `_NET_WM_STRUT_PARTIAL` and specifying the coordinates relative to the full extent of the screen?

Although I guess the math would be equivalent to setting struts in the middle of a screen, and it might break for setups where the monitors are different resolutions...

**Comment by muktupavels** [comment]
I don't know, I have not tried to look at this and not sure if I want to do that...

**Comment by welkie** [comment]
Can confirm this issue is affecting me on Ubuntu MATE 18.04 with Marco as window manager. My setup:

![https://i.imgur.com/1ls9PaA.png]

My primary monitor is HDMI-1-1, so when I maximize windows there, the bottom of the window gets hidden behind the bottom bar.

**Comment by MartinX3** [comment]
Cinnamon acts way better with multi monitors.
If you change your workplace with different monitor configurations, it works too.
Even, if you have 2 panels on every monitor.

Maybe someone want to adapt the code.

**Comment by lukefromdc** [comment]
Cinnamon is a plugin to muffin, forked from gnome-shell which is a plugin to mutter. Mutter was derived from Metacity, but even by the time of Cinnamon there was probably quite a divergence.

**Comment by awildturtok** [comment]
In which version is this supposed to land? Currently rocking from a fresh Mint install 1.20.1 and still seeing this.

**Comment by vkareh** [comment]
@awildturtok - not yet, really. I'm striving to finish this feature sometime this year, I want to make sure it lands on 1.22, but this requires changes to both the Panel and Marco, and Marco is currently being reworked to fix a bunch of other issues.

**Comment by muktupavels** [comment]
@vkareh Well that is sad response... I was hoping that you will try to implement my idea to see if that is enough or more work is needed...

**Comment by muktupavels** [comment]
https://gitlab.gnome.org/GNOME/metacity/merge_requests/2

@vkareh `_NET_WORKAREA_MONITORS` is newest property without using xinerama index... I have not pushed gtk and/or mutter changes yet.

**Comment by hinnantjames** [comment]
@ParikhMeet "I have only one primary monitor and yet this issue is observed."

(This possibly covers the multi-monitor case, see below, but I only have one.)

I had the same problem, with only one primary monitor, on Linux Mint Debian Edition 3, MATE version.  I don't know if this is exactly what fixed it, or if it will work in the multi-monitor case.

Fix: Making sure the primary monitor was set in Start Menu | Control Center | Displays, was probably what fixed it for me.  On the Displays GUI, the "Set as primary" button was ungrayed/enabled.  I clicked "Set as primary", clicked "Apply system-wide", logged out, and logged back in, and the problem was fixed.  A system message stated logging out and logging back in is required for the change to take effect, after the "Apply system-wide" button was clicked.  Before clicking "Set as primary", I did click "Detect monitors", but it didn't seem to change anything.

I think I didn't see the problem on a fresh install of LMDE 3, but the problem followed my settings when I copied my home directory, including desktop configuration settings, from an older machine which showed the problem to a new machine with fresh LMDE 3 install that didn't show the problem.

I don't know why the monitor wasn't automatically set as primary when I only had one monitor.  Possibly in copying settings between home directories on different machines the monitor change was detected by MATE and it unset the primary-monitor setting.  The problem may have shown up when I moved to the older machine from an even older one, and I might not have noticed right away.

Also, maybe the window manager is doing this because it is treating the monitor as a secondary, since it was not set as primary.  The WM may be expanding the desktop to fit the entire screen on all monitors except the primary, and on the primary expands it to fit the region above the taskbar.  Maybe when sizing the desktop the WM isn't checking monitors to see whether it is supposed to be showing the taskbar on them, but only to see if they are primary.  Some people are posting about not being able to configure the WM to show the taskbar on their secondary monitors.

I did try other things, like changing the window manager between Marco+Compositing and Marco, that didn't seem to work.  I didn't log out and log back in for those, but I think the "Set as primary" change is probably what fixed it, not the other things.

I don't see a way to unset the primary monitor setting from the GUI to test that error and fix are repeatable.  Probably there's a way to unset it from the command line, but the fix is working now, so I don't want to change it.

**Comment by hron84** [comment]
@hinnantjames I tried it, but my affected monitor is already primary and it applied system-wide (but it does not necessarily have an effect because of LightDM cursor-following feature. Window titles go behind the panel, windows maximize behind the panel. I've got a bottom panel with Win98 style task buttons so I don't lose any control over the windows but it's still frustrating.

**Comment by girifirm** [comment]
so i'm still experiencing this issue on ubuntu 18.04 Mate. Is it fixed in 20.04? :)

**Comment by schmolch** [comment]
same problem on vertical configurations. horizontal multimonitor is fine.

**Comment by bibault** [comment]
Hello, I confirm, same problem with vertical monitors on Ubuntu Mate 20.04.
It's ok with horizontal monitors.
Some new ideas to fix it ?

**Comment by embeddedt** [comment]
I'm experiencing a possibly related issue with Xubuntu 18.04 and Atril. By default, when Atril opens in maximized mode, it seems to maximize according to my screen size and not take the bottom panel (I have no top panel) into account. I'm using a single 1080p monitor.

**Comment by agude** [comment]
On 20.04 Mate I'm seeing this issue with dual horizontal monitors. 

My monitors are next to each other, so I have a left and a right monitor. Using the Mutiny panel layout, if the left monitor is primary (so the dock on the left side of the left monitor) the windows maximize and snap without overlapping the dock.

If I make the right monitor primary (so the dock is on the left side of the right monitor, hence at the "seem" between the two monitors) the windows maximize under the dock.

I have tried switching between `nvidia-driver-450` and `Nouveau` and also between `Marco Adaptive` and `Marco (No compositing)` but the bug persists.

**Comment by phord** [comment]
Same as @agude here.  Mint 20.1 + Mate.  Two horizontal monitors.  Any panel added to the seam between the monitors always occludes maximized windows.

**Comment by JakoDel** [comment]
The exact same bug @phord experienced is still here on ubuntu mate 20.04. @raveit65 @rbuj Sorry for tagging you but this is a quite spread and annoying bug.

**Comment by JakoDel** [comment]
> The exact same bug @phord experienced is still here on ubuntu mate 20.04. @raveit65 @rbuj Sorry for tagging you but this is quite spread and pretty annoying

**Comment by christopherwoodall** [comment]
It seems that the monitors are seen as a single "screen"/strut, thus moving x/y up or down moves the entire view port. Some of the commits above look to be headed in the right direction and seem to have addressed this issue by assigning individual monitors their own strut and drawing in there; see @vkareh and @muktupavels commits.

A workaround for the time being may be to  enable the "show hide" property in your panels in order to see the title bar behind them. 

![image](https://user-images.githubusercontent.com/363708/112740540-0048f580-8f4c-11eb-9c3f-2dea68872e49.png)

**Comment by muktupavels** [comment]
- https://gitlab.gnome.org/GNOME/metacity/-/merge_requests/3
- https://gitlab.gnome.org/GNOME/metacity/commit/922de13cbd51b38110cf3571131aef6ca6fa6a3a
- https://gitlab.gnome.org/GNOME/gnome-panel/-/merge_requests/3
- https://code.launchpad.net/~muktupavels/compiz/+git/compiz/+merge/377473
- https://code.launchpad.net/~muktupavels/compiz/+git/compiz/+merge/378314
- https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1300
- https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/478

**Comment by quezak** [comment]
Hi! Is the fix already released? I've just encountered this with a vertical monitor layout, in my usual office I have side-by-side monitors and there it works correctly. My guess is that it's because there's nothing  _below_ the bottom edge of the primary screen with a horizontal layout?

![image](https://user-images.githubusercontent.com/666206/121140459-2a673f80-c83a-11eb-98a9-517323779b9e.png)

**Comment by christopherwoodall** [comment]
@quezak it's not upstream yet but the issues above should help you implement it on your own system. I understand the struggle though. You can download the branch or clone the most up to date repo and install it locally.

**Comment by raveit65** [comment]
I am not sure if this is fixed now because we have one open PR.
For testings you need building marco from master with this merged PR from marco https://github.com/mate-desktop/marco/pull/678 which works well.
And you can test mate-panel master + https://github.com/mate-desktop/mate-panel/pull/1229 which isn't finished.
So i don't think it will work with a vertical panel layout.

**Comment by lukefromdc** [comment]
I haven't had this problem with my normal one panel on the bottom setup, but just tested current marco with https://github.com/mate-desktop/marco/pull/678 and mate-panel with https://github.com/mate-desktop/mate-panel/pull/1229 and got good results with a single monitor and top, bottom, and right panels.

As in my prior tests however, a problem exists when I have a second monitor running: a panel placed on the right edge of the left monitor (and presumably any other edge between monitors) will indeed get mazimized windows maximizing under it

**Comment by yderi** [comment]
Hi

Using Ubuntu Mate 20.04.2 LTS, Mate Desktop 1.24.0. 
The problem has been fixed for two monitors a while ago. But appears again if you connect a third monitor. No matter what the monitors' layout is. It seems that the system treats two monitors as a single desktop, showing icons on the left monitor and maximize windows under the Mate panel on the right monitor, the third stay unused.
Please advice.
Can do the additional tests if needed.

Regards,

**Comment by yderi** [comment]
Update. My apologies, just done more tests.

The Mate panel stays to the left. If the primary monitor set as one on the left, there is expected behavior for the maximized window.
If I set the primary monitor as one in the center, and another two to the left and right (or bottom) then we have the situation when maximized windows on the primary monitor (the one in the center) goes under the Mate panel. Mate panel itself on the right side of the primary monitor.

**Comment by raveit65** [comment]
Fixed with
https://github.com/mate-desktop/mate-panel/commit/8a380c3e9af91a726b8ed45ccf9ef64911540595
https://github.com/mate-desktop/mate-panel/commit/79a8279c52e3d0b66985cbbeaeb88bae1522c4c2
https://github.com/mate-desktop/mate-panel/commit/5bd053ad542479eaec4166e45195c5e911472f88

**Comment by Tectract** [comment]
I'm on a fresh install of Debian, linux image 5.10, running compiz under mate. I'm seeing this problem still. I have a second monitor placed above my primary monitor, and this causes the primary monitor to have windows maximize "under" the menus. Please help? I see this ticket is marked as solved and closed... So how do I implement the fix?

**Comment by djmattyg007** [comment]
You'll probably need to wait until mid-2023 at the earliest, when Debian 12 is likely due to be released.

**Comment by Tectract** [comment]
any way to backport the fix? I don't want to have to update my OS, lol

**Comment by raveit65** [comment]
> any way to backport the fix? I don't want to have to update my OS, lol

What a question......
We are MATE not Debian and fixes are in a mate-panel-1.26.2 release.
Sorry we are not responsible for debian updates politics. File out a ticket at debian bug reporting system.

**Comment by djmattyg007** [comment]
@Tectract You shouldn’t use a distribution that deliberately doesn’t update things in the name of “stability”, and then complain that you don’t get updates. Use a distribution that’s more appropriate for desktop use.

if you’re a fan of the packaging ecosystem, Ubuntu MATE 22.04 LTS will be out in the next few months. You could wait until then.

**Comment by yderi** [comment]
Hello everyone

I'm using Ubuntu Mate 21.04 with all the latest updates. But the Mate Panel is still 1.26.00. Waiting for this fix all way long since 16.04. 
Can I expect the fixes for this in the Ubuntu Mate release 21.04?

If not, how can I fix the problem by myself? (Any recipes?)

Thank you to everyone.

**Comment by embeddedt** [comment]
I believe 21.04 is unsupported (you should upgrade to 21.10), and it appears the fix wasn't released till December, so it won't be available till 22.04 unfortunately.

I would suggest using a rolling-release distro if the Ubuntu update pace is too slow for your preference.

**Comment by Tectract** [comment]
I'm not using Ubuntu, I'm using Devuan. Stability is one of the most important parts of linux, the people over at Ubuntu have forgotten that, their release cycle is far too fast and they don't spend enough time fizxing huge bugs, like this one. That's why Ubuntu has these graphical artifacts and can't handle multiple-monitor output, a very basic function that Windows can handle easily, even now, in 2022.

**Comment by yderi** [comment]
Thank you to everyone.

> I believe 21.04 is unsupported (you should upgrade to 21.10), and it appears the fix wasn't released till December, so it won't be available till 22.04 unfortunately.
> 
Again, my apologies. Right now I'm using 21.10 (it's my typo mistake in one post above), and you are right, fixes are not released for Feb 2022. 
Trying to compile the 1.26.2 myself. Will let you know once I'm abe to accomplish it.

**Comment by yderi** [comment]
I've been able to compile and install mate-panel 1.26.2 under Ubuntu Mate 21.10. 
But now I'm missing "mate-indicator-complete" and other indicators such as Sensors applet, System monitor, CPUfreq, etc. You cannot find and re-add them to the mate-panel.
If someone knows how to fix it, please advise.
Right now uninstalled the 1.26.2 (reverted to 1.26.0), should I also compile the other indicators from the source?

**Comment by Tectract** [comment]
Yes, it doesn't really make sense that we should have to wait for an OS version update, to implement an update / patch in mate. Does it rely on a new libC or a new version of python? Not that I can tell. So it should be able to be fixed with just a package update, right?

**Comment by raveit65** [comment]
Please talk with unbuntu or debian bug reporting system. This is not the place to tallk about update problems of you distro.
Our job is done.
... conversation will be locked.
