### ISSUE TITLE
panel missing border (for themes that should have border)

### ISSUE THREAD

**Issue by AprilVRose** [mate-desktop/mate-panel#344]
Prior to the recent update to Mate 1.10 in Fedora 21, TraditionalOk drew a border at the edge of the panels; in Fedora 22 (and Fedora 21 after the Mate 1.10 update), this border is gone. See attachment Fedora22_TraditionalOk.png which illustrates this by using a background which is the same color as the panel.

![fedora22_traditionalok](https://cloud.githubusercontent.com/assets/14043682/9568878/c03da876-4f25-11e5-8061-c738ca860286.png)

This becomes a larger problem when the panel is set to autohide -- when the user hovers the mouse at the top edge of the screen to bring the panel up, it covers the titlebar of a maximized application, and since the panel is the same color as the application, there's no distinction between the panel and the application window. See attachments comparing Fedora21_Pre-Mate_1.10.png and Fedora22_Mate_1.10.png.

![fedora21_pre-mate_1 10](https://cloud.githubusercontent.com/assets/14043682/9568879/c9a08b86-4f25-11e5-9d0a-1fb6ca3a9230.png)
![fedora22_mate_1 10](https://cloud.githubusercontent.com/assets/14043682/9568881/cfde9f10-4f25-11e5-82a7-bb332a1ba7ac.png)

The same issue can apply with the bottom panel in certain applications.

Steps for reproduction:
1) Change theme to TraditionalOk
2) Maximize the "Appearance Preferences" window (or any window)
3) Set the top panel to Autohide
4) Move your mouse to the top of the screen to ensure the top panel is visible ... in Mate 1.8 you will see a border drawing a distinction between the panel and the window that is under it; in Mate 1.10 there is no such border.

By the way, this issue isn't specific to TraditionalOk -- GreenLaguna is also affected. BlackMate is also affected, but the border color was so close to the panel color in that theme that the difference is not really noticeable. The other themes never had panel borders so are not affected.

In Fedora 21, I can confirm that the change which removed the border is in one of the following packages (or between these versions and the unaffected versions noted below):
mate-panel (1.10.1-1)
 mate-panel-libs (1.10.1-1)
mate-desktop (1.10.1-3)
 mate-desktop-libs (1.10.1-3)
pluma (1.10.2-1)
 pluma-data (1.10.2-1)

The following are the package versions prior to update (not affected by the missing border issue):
mate-panel (1.8.1-4)
 mate-panel-libs (1.8.1-4)
mate-desktop (1.8.2-2)
 mate-desktop-libs (1.8.2-2)
pluma (1.8.1-3)
 pluma-data (1.8.1-3)

Feel free to reference my original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1226589
##

**Comment by nineinchnails** [comment]
I can confirm! Linux Mint 17.2. Mate-panel will not render borders.

![screenshot](https://cloud.githubusercontent.com/assets/12740958/10560583/e2d6aa70-74d4-11e5-96b4-7bcb7325de66.png)

As you can see, the border is not displaying, even though it should be. 

This effects ALL themes on my system.

**Comment by thachngopl** [comment]
Here is a workaround for Mint-X theme (Linux Mint MATE 18.3). Added these lines to the end of mate-applications.css
```css
.mate-panel-menu-bar,
.gnome-panel-menu-bar,
PanelToplevel.background {
    padding-top: 2px;
    background-clip: padding-box;
    background-color: transparent;
    background-image: linear-gradient(to bottom, @button_hover_raised_bg_a 1%, black);
}

.mate-panel-menu-bar GtkGrid,
.gnome-panel-menu-bar GtkGrid,
PanelToplevel.background GtkGrid {
    background: @theme_bg_color;
}
```
The result:
![screenshot at 2018-04-14 14-45-54](https://user-images.githubusercontent.com/16706272/38765832-1a56b008-3ff3-11e8-82b3-b1253173c209.png)

**Comment by mknepper** [comment]
Holy crap, I never though anyone would actually come up with a fix for this. Major kudos to you! Any word on whether it will get officially fixed?

**Comment by raveit65** [comment]
Any word on whether it will get officially fixed?
This hack works only if you use one bottom panel.
There are other distros which use another panel layout........

**Comment by thachngopl** [comment]
Yes, this is a temporary solution only. I have been waiting for the fix in 2 years!!!

**Comment by raveit65** [comment]
With that commit https://github.com/mate-desktop/mate-panel/commit/c4aedbddc01da6c0bf439e4229d77ae4c137df45
An example css for Menta and other light themes which can be used in
~.config/gtk-3.0/gtk.css
```
.mate-panel-menu-bar.horizontal.top > grid {
    border-style: outset;
    border-width: 0px 0px 1px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.horizontal.bottom > grid {
    border-style: outset;
    border-width: 1px 0px 0px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.vertical.left > grid {
    border-style: outset;
    border-width: 0px 1px 0px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.vertical.right > grid {
    border-style: outset;
    border-width: 0px 0px 0px 1px;
    border-color: rgba(0, 0, 0, 0.23);
}
```

**Comment by muesli4** [comment]
I use Blue-Submarine and now suddenly a very light border appeared. For dark backgrounds this draws way too much attention to the border. Any idea how I get the old behavior back? Should I go to that particular theme?

**Comment by raveit65** [comment]
All is written here to disable the border.
Works for all themes.
https://github.com/mate-desktop/mate-panel/issues/344#issuecomment-401452555

**Comment by raveit65** [comment]
@muesli4 
See https://github.com/mate-desktop/mate-themes/issues/232#issuecomment-412418162

**Comment by mknepper** [comment]
Did this ever get fixed? I haven't used MATE because of this one thing, I can't get my themes to work. Redmond, for example, -should- have borders on the panels, like on Windows 98.

**Comment by raveit65** [comment]
This is already fixed by https://github.com/mate-desktop/mate-panel/commit/2c8de940026ce9a933dedc378a17d7c5e42bbb74
You can add something like this to your theme
https://github.com/mate-desktop/mate-themes/commit/8c49f552749d3532efc376006f4ec70801cf0d0d#diff-440857c228e0489f0ffddaba387ea807R250
Or use mate-themes.

**Comment by mknepper** [comment]
This still isn't working. I selected mate-themes, made sure to show the package information and made sure that I have a mate theme selected. Using Xubuntu 18.04 LTS. 

![stillnotworking](https://user-images.githubusercontent.com/12740958/47805566-9fc71700-dd05-11e8-86c8-fc3018c78dbf.png)

Is 18.04 too old? Am I doing something?

**Comment by raveit65** [comment]
You need mate-panel-1.20.3 and mate-themes-3.22.18.
If only the right version of mate-themes are missing than download the tarbal  and copy them to your theme dir under /usr/share/themes.
http://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.18.tar.xz

**Comment by NinjaCowboy** [comment]
This still isn't working!!! I tried adding this to my gtk.css, and while the background color does take effect for the entire panel, only the individual widgets within the panel have the borders.
```
.mate-panel-menu-bar,
.gnome-panel-menu-bar,
PanelToplevel.background {
	background-image: none;
	border: 3px solid magenta;
	background-color: yellow;
}
```
