### ISSUE TITLE
Mate panel drawer applet doesn't work - mostly

### ISSUE THREAD

**Issue by rebelxt** [mate-desktop/mate-panel#44]
I have problems with the mate panel drawer applet. I add it to the panel, add an applet to the drawer, and may or may not have access to that applet. If I reboot, the drawer never works.

I have tested this with Mint 13 Mate 32 bit and 64 bit, on a bare metal install and under VirtualBox on two different computers. I even installed Mate 1.4 on one of the VirtualBox Mint test machines; same results. I also see the same results in a VirtualBox installation of Salix Mate 13.37-64.

However, the drawer applet in an installation of SnowLinux 2 Cream 64bit does work properly. I can see that the SnowLinux implementation does handle the panel configuration files differently than the other implementations.  This could imply that they have modified their panel programs.

The installation of Mate 1.4 on a Mint 13 test machine, and seeing it fail, leads me to believe that SnowLinux has a fix for the problem. If I'm wrong, and the Mint people have screwed up their implementation, let me know, and I'll go bug them.

The other possibility that comes to mind is that SnowLinux 2 is using GTK2, where the other implementations are using GTK3 in their desktop environments. Could that be the incompatibility? If so, whose problem is it?

**Comment by monsta** [comment]
Looks like it's still an issue in 1.10. I've added a drawer, put a trash applet inside it for a test, then logged out and back in. Drawer won't open now and I get this in ```~/.xsession-errors``` file after every click on drawer:

```
(mate-panel:14819): Gtk-CRITICAL **: IA__gtk_widget_map: assertion 'gtk_widget_get_visible (widget)' failed
```

**Comment by NiceandGently** [comment]
confirmed that adding the trash applet to drawer breaks it

**Comment by monsta** [comment]
Everybody: please try https://github.com/mate-desktop/mate-panel/pull/319 and check if the issue goes away.

**Comment by samandiriel** [comment]
What release will this fix go into then?

**Comment by monsta** [comment]
It's in 1.10.1 already

**Comment by samandiriel** [comment]
Has it been released to the updates channel?  I tried adding a drawer and then adding some custom app launchers to it, and I didn't even have to log out and in again before it vanished itself itself behind the panel and also stretched itself to the top of the screen when I clicked on where the icon should have been.  Using mate-panel 1.10.0-1, which is ambiguous enough that I don't know if that's 1.10.1 or not...
![screenshot-gir1 2-mate-panel properties](https://cloud.githubusercontent.com/assets/3135396/9684523/ff855b6e-52cc-11e5-9cc7-e16d49c1a3b8.png)

**Comment by monsta** [comment]
You have upstream version ```1.10.0```. All the stuff after ```'-'``` character is standard Debian/Ubuntu suffix for specifying distro's own version/release of package.
Wait for @clefebvre to push all 1.10.x packages to Mint repos :smile:

**Comment by monsta** [comment]
That said, you seem to have a different issue with drawer. I think it has been reported here as well.

This issue is closed because the original reporter's problem has been fixed:

> I have problems with the mate panel drawer applet. I add it to the panel, add an applet to the drawer, and may or may not have access to that applet. If I reboot, the drawer never works.

**Comment by samandiriel** [comment]
Oh - drat.  OK... do you happen to know which issue it is, so I can keep an eye on progress?  It's a huge downer for me, I like to organize using drawers and it's sad-making that they're still not working right :(
