### ISSUE TITLE
[1.18.1] mintMenu in left panel is unavailable

### ISSUE THREAD

**Issue by WPo** [mate-desktop/mate-panel#573]
After updating to Mate 1.18.1 yesterday, my mintMenu on the upper side of the left panel disappeared. There was only a black box in full width of 150px of the panel, but no responsiveness. Re-insert of the mintMenu in this panel doesn’t help. Still there’s a black box.

In other panels (on the right or the top of the screen) I can place and use mintMenu without problems. Moving a mintMenu from there to the left panel still results in a black non-responsive box.

I thought, renaming the userspace dirs for mintMenu settings could help. So I renamed
- /home/wpo/.linuxmint/mintMenu
- /home/wpo/.mateconf/apps/mintMenu

and re-inserted the mintMenu in the left panel. No success, even after reboot! Ok, I’ve made these changes undone.

Oh, all panels I use are auto-hiding to maximize the remaining space on the desktop. Also I’ve read something about a switched behaviour of the setable border around the menu box. I had set a border of 3px green. Now, after some playing with GTK3+-themes and the appearance, I cannot verify or re-enter the settings for this border in the preferences. I think, this feature is gone completely. Instead, there is a common window border around the menu. It looks unpleasant.

P.S.: The first call to the mintMenu is delayed some seconds. Is it possible to do the caching of all needed data e.g. 8-10 seconds after launch with very low priority?

P.P.S.: The Mate main menu produces very large space consumption, as the symbol is placed ~50px to the bottom, where the huge arrow to the right is placed correctly.

LMDE 2, Linux 3.16, Mate 1.18.1

Greetings – WPo

**Comment by raveit65** [comment]
As the name says 'mintmenu', this package is not part our suite.
Please file out a report at linuxmint.

**Comment by WPo** [comment]
@raveit65: You haven’t read my post. mintMenu isn’t the problem, Mate panel is, because it doesn’t accept the mintMenu on the left panel! Instead of choking off this issue item, you could contribute to the Mate project by finding the bug. But ok, your method is the easiest for you.

**Comment by raveit65** [comment]
Other applets doesn't have this issue.
Again, file out a report at linuxmint, and if those developers say it is a panel bug i am happy to re-oppen the issue.

**Comment by XRevan86** [comment]
@WPo, what version of mintMenu do you have?

**Comment by clefebvre** [comment]
@WPo, this looks like the issue that @monsta fixed in mintmenu: 

https://github.com/linuxmint/mintmenu/commit/2c8a68633eb54781b0284abc7371fc75fad25877

That fixed shipped with version 5.7.9 in LMDE.

**Comment by WPo** [comment]
@clefebvre , @XRevan86: Oh, it’s mintMenu 5.7.8
Tomorrow I’ll read more about this theme. Thank you for your response!

**Comment by WPo** [comment]
After updating mintMenu 5.7.8 to 5.8.0, still the same issue resided. But then, after reboot and re-insert the mintMenu in the left panel, 8-10 instances of apt-cache.py (or similar name) appeared in my mate-system-monitor, who consumed ~300% CPU each ;-] After an hour all instances were finished and the mintMenu now is available again. Thanks!
