### ISSUE TITLE
System tray drawing issues on HiDPI display 

### ISSUE THREAD

**Issue by omgold** [mate-desktop/mate-panel#668]
#### Expected behaviour
- system tray contents look the same as on LoDPI displays (except for scaling)
 
#### Actual behaviour
- 'half' copies of Icons are often appearing on the left of the tray
- language indicator text is not scaled up correctly 

Image:
![tray](https://user-images.githubusercontent.com/11440198/31309669-482702b0-ab8a-11e7-80e6-0ac33993d08e.png)

#### Steps to reproduce the behaviour
Run MATE with system tray active in panel. Set resolution in Appearance->Fonts in  to 150 dpi. Set panel height to 32 pixels.

#### MATE general version
1.18

#### Package version
mate-panel-1.18.4-1-x86_64.pkg.tar.xz

#### Linux Distribution
Arch

**Comment by monsta** [comment]
@flexiondotorg: would https://github.com/mate-desktop/mate-panel/commit/bdee659c5338a846c941dc716f2df34c01d3c60d fix this?

**Comment by flexiondotorg** [comment]
@monsta No. That forces the panel to not use scaling so it fits to the screen boundaries. We need to dynamically pickup the GTK scale factor and apply multipliers to panel sizes, fonts etc.

**Comment by monsta** [comment]
Sigh, more work again...

**Comment by omgold** [comment]
I have to add a correction: The problem with the half-icon to the left, appears also on LoDPI screens:

![systray-bug](https://user-images.githubusercontent.com/11440198/33267826-300ec4ba-d37b-11e7-84d0-912bef4a9ad4.png)

**Comment by monsta** [comment]
Something like that has been reported at https://github.com/mate-desktop/mate-panel/issues/610, but with other tray icons (not the keyboard layout one).

**Comment by omgold** [comment]
It's not specific to the keyboard layout icon. It usually is simply the leftmost one, or second-to-leftmost.

**Comment by lukefromdc** [comment]
The more general version of this, (with one icon being partially rendered) seems to be an old bug going back at least as far as GTK3 builds of mate 1.10. I've seen it on rare occasions for years but never consistantly

**Comment by flexiondotorg** [comment]
This was fixed via https://github.com/mate-desktop/mate-panel/pull/710 and is now released in MATE Desktop 1.20.

**Comment by omgold** [comment]
Just tired version 1.20.0 (on a non-hidpi display). The problem is still there, looking exactly the same as before.

**Comment by raveit65** [comment]
> Just tired version 1.20.0 (on a non-hidpi display). The problem is still there, looking exactly the same as before.

see https://github.com/mate-desktop/mate-settings-daemon/issues/213#issuecomment-365053168
You need to recompile the panel with --with-in-process-applets=all

**Comment by clayfreeman** [comment]
For others using Gentoo, the flickering tray icons can be fixed by running the following:

```bash
EXTRA_ECONF="--with-in-process-applets=all" emerge -a '>=mate-base/mate-panel-9999'
```

**Comment by omgold** [comment]
Interesting. That actually seems to work. But I am confused about why this is necessary. And if it is, shouldn't the option be the default?

**Comment by lukefromdc** [comment]
In-process applets are treated in the code as part of the panel itself. My guess is that something in the panel code is getting applied to ALL applets, and for out-of-process applets then gettting applied again in the case of the applets that ship with the panel when running as a separate process.

**Comment by monsta** [comment]
@omgold: for clarification... do you still see the problem reported in #610 (which seems independent from DPI of display), or the problem shown on your screenshot at the top?

**Comment by omgold** [comment]
On my hidpi I currently cannot reproduce the issue at all (even with 1.18). Unfortunately I never figured out how to trigger it. But yesterday on a lodpi I saw the problem above, even with the configure option.

**Comment by omgold** [comment]
Correction, everything is only fine on the hidpi when still running 1.18 and just restarting mate-panel. With everything on 1.20 desktop is completely screwed up. Will open a separate ticket for that.

**Comment by monsta** [comment]
Check https://github.com/mate-desktop/mate-settings-daemon/issues/213, it's opened in the wrong repo but it's also about visual issues in the panel with HiDPI.
