### ISSUE TITLE
File Manager Gets Stuck in Panel

### ISSUE THREAD

**Issue by StealthStalker** [mate-desktop/mate-panel#860]
#### Expected behaviour
When File Manager is Minimized into the Panel it should be able to be Maximized from there.

#### Actual behaviour
When File Manager is Minimized into the Panel it cannot be Maximized from there.  I constantly have to Right Click "Close" and start over.

#### Steps to reproduce the behaviour
Open File Manager with something like a USB Flash Drive with files on it, then Minimize it.  Open the Menu Once or more, then try to Maximize the File Manager from the Panel again, and it won't Maximize.

#### MATE general version
Linux Mint Mate , 18.xx Series
All computers regardless of graphics
64 bit
#### Package version
Don't know this

#### Linux Distribution
Mint Mate 18.0-18.1-18.2-18.3

**Comment by lukefromdc** [comment]
Are you clicking the button with the left click to bring the window back up, or trying to maximize directly from the button's right-click menu? I just found that with every program I tried, a right-click button menu maximize attempt does nothing until you left-click the button to display the window. While the window is not minimized, the "Maximize" and "Unmaximize" menuitems in the right-click menu act as expected.

**Comment by StealthStalker** [comment]
Left Click, sorry I missed this post lukefromdc!

I don't understand this site format either.  This is a huge issue and I cannot believe that more folks don't shout out about it.  I've tried this with multiple iso's all verified, on different computers, over years of time, really, why is there not more folks shouting about this?  I've tried it on Intel, AMD, Laptops, Desktops, AIO's, really really really!  I have seen a few folks talk about it but not as many as I would expect.  Mostly on the Mint Forums, a few folks there have seen it, but not the exact way I am seeing it.  

Am I even in the right place for bug reports?  Seems like I posted this somewhere else also but don't remember where now.

Thanks, Stealth

**Comment by StealthStalker** [comment]
Did you try this luke:
**_"Open File Manager with something like a USB Flash Drive with files on it, then Minimize it. Open the Menu Once or more, then try to Maximize the File Manager from the Panel again, and it won't Maximize."_**

**Comment by lukefromdc** [comment]
I just tested this, it looks like this is specific to the right-click menu only, as clicking on the panel button containing the minimized file browser window will reliably bring it up. If you selected "maximize" from the right-click menu and that did nothing, it will now come up maximized.

I never saw this because maximizing a window from minimize is never part of my normal workflow. This shows why more testers is always good, as different workflows will find or miss different bugs

**Comment by lukefromdc** [comment]
Note that (at least here) this is ALL applications and applies only to maximizing directly from the minimized window's panel button using the right-click menu.

**Comment by StealthStalker** [comment]
> I just tested this, it looks like this is specific to the right-click menu only, as clicking on the panel button containing the minimized file browser window will reliably bring it up.
> 
No, it does not, and, the parameter was: You have to open the Menu once first while File Manager is Minimized, the Mate distro Menu, not File Manager.
> I never saw this because maximizing a window from minimize is never part of my normal workflow. This shows why more testers is always good, as different workflows will find or miss different bugs.
> 
Seems like here you are saying you do see an issue?
> EDIT: what I have here is :
> left-click to unminimize: absolutely reliable
Not for me.  Minimize>Open Menu>Attempt to Maximize and it won't.
>  
Thanks for the Reply!

**Comment by StealthStalker** [comment]
**Steps to reproduce the behaviour:**

**_"Open File Manager with something like a USB Flash Drive with files on it, then Minimize it. Open the Menu Once or more, then try to Maximize the File Manager from the Panel again, and it won't Maximize."_**

**Comment by StealthStalker** [comment]
Another interesting note, the little letters on the File Manager Icon will turn BOLD when this happens.

**Comment by StealthStalker** [comment]
Here is a good link where others are having the same issue.
https://forums.linuxmint.com/viewtopic.php?f=206&t=266561

**Comment by lukefromdc** [comment]
I am wondering if this is actually a bug in libwnck, which creates the menus
in question. Different versions of libwnck could easily explain different behavior
here. I have the newest version(3.32 I think it is) installed from  a local build.

When I get home I will see if gnome-panel also does this, though the codebase is
closely related so this is not dwfinitive.

**Comment by StealthStalker** [comment]
If we can find a fix I would be very happy!

**Comment by StealthStalker** [comment]
@lukefromdc:  I should also say that Mate is my favorite desktop and this is why I've come back to this topic.  Right now, I cannot find a better Desktop Experience, and will start using it again if there is a fix coming.

Also, I tried this in Mint Mate 19.0 also, and the same issue exists.

**Comment by lukefromdc** [comment]
I just duplicated this in gnome-panel, which like mate-panel uses libwnck to create the tasklist's list of windows and create the menus.

I cannot fix a bug that isn't in MATE at all, and this really sounds like a libwnck issue. You might want to open an issue there, as they might not even be aware of this.

**Comment by StealthStalker** [comment]
Where would I do that, here?
https://launchpad.net/ubuntu/+source/libwnck/+bugs

**Comment by StealthStalker** [comment]
> I just duplicated this in gnome-panel, which like mate-panel uses libwnck to create the tasklist's list of windows and create the menus.
> 
> I cannot fix a bug that isn't in MATE at all, and this really sounds like a libwnck issue. You might want to open an issue there, as they might not even be aware of this.

This don't make sense to me?  You said they both use libwnck and you cannot see the issue in gnome-panel?  gnome-panel don't exist in Mate does it?  Are you testing this in Mate or not?  Sounds like you are using Ubuntu to test this?

**Comment by lukefromdc** [comment]
You misread ne: gnome-panel is no part of MATE but mate-panel is a fork of it,
and both use libwnck. BOTH mate-panel and gnome-panel had this issue in my
test, rhey behaved exactly the same.

**Comment by lukefromdc** [comment]
That's a good place, as libwnck devs will see it there and if the package came from
Ubuntu it should be reported there first.Also distro bug reports can catch any disto-
specific issues and might get listened to first by upstream devs.

**Comment by StealthStalker** [comment]
> You misread ne: gnome-panel is no part of MATE but mate-panel is a fork of it, and both use libwnck. BOTH mate-panel and gnome-panel had this issue in my test, rhey behaved exactly the same.
> […](#)
> On 5/24/2019 at 11:37 AM, "StealthStalker" ***@***.***> wrote: > I just duplicated this in gnome-panel, which like mate-panel uses libwnck to create the tasklist's list of windows and create the menus. > > I cannot fix a bug that isn't in MATE at all, and this really sounds like a libwnck issue. You might want to open an issue there, as they might not even be aware of this. This don't make sense to me? You said they both use libwnck and you cannot see the issue in gnome-panel? gnome-panel don't exist in Mate does it? Are you testing this in Mate or not? Sounds like you are using Ubuntu to test this? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#860 (comment)](https://github.com/mate-desktop/mate-panel/issues/860#issuecomment)- 495680981

They did, okay, that is great that you are seeing it and it makes sense to you.  I will hope they find something to fix soon as I wanted to install Mate now, but may install something else as it may take them a while.

**Comment by StealthStalker** [comment]
No resolution?

**Comment by lukefromdc** [comment]
We can't fix this here if the bug is in libwnck

**Comment by muktupavels** [comment]
Minimize and Maximize are completely different things... To me it sounds like you want to Unminimize! Maximization is about making window fullscreen minus panels and docks.

Anyway, clicking Maximize when window is minimized works - the state is sent to window manager and if you open menu again you will see that it now offers options to Unminimize and Unmaximize. Unminimize it and you will see your window maximized.

**Comment by lukefromdc** [comment]
OK, what that tells me is that "maximize" could just be disabled (greyed out) when minimized, or the code for maximize could when minimized unminimize first (or maybe second so as not to render twice). Still, I think these menus come directly from libwnck, because I was never able to find them in mate-panel's code for theming purposes back in 2015.

**Comment by StealthStalker** [comment]
> Minimize and Maximize are completely different things... To me it sounds like you want to Unminimize! Maximization is about making window fullscreen minus panels and docks.
> 
> Anyway, clicking Maximize when window is minimized works - the state is sent to window manager and if you open menu again you will see that it now offers options to Unminimize and Unmaximize. Unminimize it and you will see your window maximized.

Incorrect!  

I can see this was a waste of time and I don't know where to go from here.  If those who maintain Mint Mate or whatever don't care then why should I?  I'm just a user and not a software writer etc. but now will not bother running Mint Mate as I need to be productive, and this is not productive.

If I'm constantly working with File Manager, and Minimizing Windows often, and they get stuck in the Panel that slows me down and frustrates me.  It's just a simple task that works in every other OS and distro I've even used, so I don't know why it is so confusing to everyone.  

Minimize by - or Clicking on the Icon in the Panel, either way it will get stuck after you Open the Menu once.  It seems when another program is opened or Maximized, like a Browser, then I can go back and Click on Panel File Manager Icon and it will Maximize.  

Thanks for the effort guys but I'm out!  I've spent far to much time on this already.

**Comment by StealthStalker** [comment]
Again, what a waste of time for everyone?

**Comment by vkareh** [comment]
@StealthStalker - This was resolved here: https://github.com/mate-desktop/marco/pull/528 that's why this ticket was closed. The MATE developers cared enough to work on it, test it, and approve the merge, so I don't think anyone's time was wasted :P

**Comment by StealthStalker** [comment]
First off  Apologies, but that thread made no sense to me and still don't.  Perhaps I'm lost by all the technical jargon?
**_"For example, unmaximizing a minimized window:"_**  Comment by you don't even make sense to me?  How would you unmaximize a minimized window LOL!  

Would you explain to me how I would get a distro with the improvements?  Is it as simple as running updates to current to get the fix?  

How long will it be before something like this is refreshed at the Linux Mint Repositories for example?  I like to use Linux Mint Mate to recover files from the dreaded MS OS's, and Mate is the best for this as the File Manager and the menu are all very nice!  I would also like to install Mate again after years of not running it because of this issue, so as you can see this is important to me as a Linux user.  When one is constantly moving files around and such this was a really annoying issue, so I'm not sure why no one ever reported it.  Sure it is still usable but not the way I use my File Manager, always minimizing a windows etc.

Thanks

**Comment by vkareh** [comment]
Heh, but the maximizing a minimized window is true, though, at least from the point of view of the window state, but that's beside the point, I've disabled that since it's just confusing.

Updates depend on the Mint team, and I'm not familiar with their release cadence, but this won't be part of the stable MATE release until January or February, and then Mint would need to include them in their following release, so some next year? Sorry, that's how we currently handle this... It takes time for these things to trickle down to specific distro releases :/

Maybe someone from the Mint team can create an installable package? Maybe they have a developer preview of the latest builds?

**Comment by StealthStalker** [comment]
Can't I just go to mate.org and download the new code and install it to Mint Mate LOL?  I'm sure it's not that simple.

**Comment by lukefromdc** [comment]
You would have to set up a build environment for MATE and compile the packages, as these are the source code.

**Comment by StealthStalker** [comment]
What happened to this conversation?  Did it move somewhere else...I forget.  Or can I not post here anymore?
